branch-defaults:
  default:
    environment: Udagramapi-env-1
    group_suffix: null
global:
  application_name: udagram-api
  artifact: www/Archive.zip
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  deploy: null
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
